name: Pomelo Challenge Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download Dependencies
        run: ./gradlew androidDependencies

      - name: Check Kotlin Formatting
        run: ./gradlew ktlintCheck --continue

      - name: Run Tests
        run: ./gradlew test

      - name: Build & Test Project
        run: ./gradlew assemble --continue